# Generated by Django 2.2.7 on 2020-03-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=256)),
                ('college_code', models.CharField(max_length=100)),
                ('college_departments', models.TextField(help_text="dept's must be separated by commas.", max_length=1000000)),
                ('college_address', models.TextField(max_length=10000)),
                ('college_contact_no', models.CharField(max_length=256)),
                ('college_email', models.CharField(max_length=256)),
                ('chat_room_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='ma',
        ),
        migrations.AlterField(
            model_name='chat_room_messages',
            name='M9',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chat_room_messages',
            name='chat_room_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.college'),
        ),
        migrations.DeleteModel(
            name='chat_room',
        ),
    ]
