# Generated by Django 2.2.7 on 2020-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20200310_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M11',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M12',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M13',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M14',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M15',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M16',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M17',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M18',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M19',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M20',
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M10_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M10_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M1_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M1_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M2_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M2_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M3_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M3_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M4_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M4_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M5_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M5_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M6_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M6_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M7_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M7_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M8_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M8_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M9_profile_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chat_room_messages',
            name='M9_sent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='chat_room_messages',
            name='M10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat_room_messages',
            name='M9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
