# Generated by Django 2.2.7 on 2020-03-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20200310_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M10_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M10_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M1_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M1_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M2_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M2_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M3_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M3_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M4_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M4_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M5_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M5_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M6_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M6_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M7_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M7_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M8_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M8_sent_by',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M9_profile_path',
        ),
        migrations.RemoveField(
            model_name='chat_room_messages',
            name='M9_sent_by',
        ),
    ]
