# Generated by Django 2.2.7 on 2020-02-09 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alumniDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Regno', models.CharField(max_length=256)),
                ('Email', models.EmailField(default='default@gmail.com', max_length=256)),
                ('DOB', models.DateField(help_text='YYYY-MM-DD', max_length=200)),
                ('College', models.CharField(max_length=256)),
                ('Dept', models.CharField(max_length=200)),
                ('Batch', models.IntegerField(choices=[('1970-1974', '1970'), ('1971-1975', '1971'), ('1972-1976', '1972'), ('1973-1977', '1973'), ('1974-1978', '1974'), ('1975-1979', '1975'), ('1976-1980', '1976'), ('1977-1981', '1977'), ('1978-1982', '1978'), ('1979-1983', '1979'), ('1980-1984', '1980'), ('1981-1985', '1981'), ('1982-1986', '1982'), ('1983-1987', '1983'), ('1984-1988', '1984'), ('1985-1989', '1985'), ('1986-1990', '1986'), ('1987-1991', '1987'), ('1988-1992', '1988'), ('1989-1993', '1989'), ('1990-1994', '1990'), ('1991-1995', '1991'), ('1992-1996', '1992'), ('1993-1997', '1993'), ('1994-1998', '1994'), ('1995-1999', '1995'), ('1996-2000', '1996'), ('1997-2001', '1997'), ('1998-2002', '1998'), ('1999-2003', '1999'), ('2000-2004', '2000'), ('2001-2005', '2001'), ('2002-2006', '2002'), ('2003-2007', '2003'), ('2004-2008', '2004'), ('2005-2009', '2005'), ('2006-2010', '2006'), ('2007-2011', '2007'), ('2008-2012', '2008'), ('2009-2013', '2009'), ('2010-2014', '2010'), ('2011-2015', '2011'), ('2012-2016', '2012'), ('2013-2017', '2013'), ('2014-2018', '2014'), ('2015-2019', '2015')])),
                ('PhoneNo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='additionalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=256)),
                ('dob', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=256)),
                ('yoc', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
