# Generated by Django 2.2.7 on 2020-02-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200209_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidatabase',
            name='Email',
            field=models.EmailField(blank=True, max_length=256),
        ),
    ]
