# Generated by Django 2.2.7 on 2020-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200209_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidatabase',
            name='Email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
