# Generated by Django 2.2.7 on 2020-03-20 08:58

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200318_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluser',
            name='profile',
            field=models.ImageField(default='static/Anonymous.png', upload_to=app1.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='additionaluser',
            name='dept',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], max_length=256),
        ),
        migrations.AlterField(
            model_name='alumnidatabase',
            name='College',
            field=models.CharField(choices=[('Government college of engineering, salem', 'Government college of engineering, salem')], max_length=256),
        ),
        migrations.AlterField(
            model_name='alumnidatabase',
            name='Dept',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], max_length=200),
        ),
    ]
