# Generated by Django 2.2.7 on 2020-03-20 09:01

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200320_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluser',
            name='profile',
            field=models.ImageField(default='media/Anonymous.png', upload_to=app1.models.user_profile_path),
        ),
    ]
