# Generated by Django 2.2.7 on 2020-03-20 09:40

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200320_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluser',
            name='college',
            field=models.CharField(choices=[('Government college of engineering, salem', 'Government college of engineering, salem'), ('Government College of Engineering, Bargur', 'Government College of Engineering, Bargur')], max_length=256),
        ),
        migrations.AlterField(
            model_name='additionaluser',
            name='profile',
            field=models.ImageField(default='Anonymous.png', upload_to=app1.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='alumnidatabase',
            name='College',
            field=models.CharField(choices=[('Government college of engineering, salem', 'Government college of engineering, salem'), ('Government College of Engineering, Bargur', 'Government College of Engineering, Bargur')], max_length=256),
        ),
    ]
