# Generated by Django 2.2.7 on 2020-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200320_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluser',
            name='phone',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
